version: "3"
services:
    web:
        env_file:
            - .env
        image: bryanjlittlefield/tugboat-php:${PHP_VERSION}
        container_name: ${PROJECT_NAME}_web
        volumes:
            # Mount Files to Container on build
            - ./scripts/build-files:/usr/local/bin/build-files
            # Mount Apaches Log Files on Host
            - ./var/log/apache2:/var/log/apache2
            # Example of a Host Mounted Volume
            - .${DOCUMENT_ROOT}:${DOCUMENT_ROOT}
            # Example of a Named Data Volume
            #- web-data-volume:/var/www/html
        ports:
            - "80:80"
            - "443:443"
            - "1080:1080"
            - "3001:3001"
            - "3000:3000"
            - "10000:10000"
            #- "2222:22"
        links:
            - db:mysql
            - redis:redis
            - mailhog:mailhog
        restart: on-failure
    db:
        env_file:
            - .env
        image: bryanjlittlefield/tugboat-mysql:${MYSQL_VERSION}
        container_name: ${PROJECT_NAME}_db
        volumes:
            # Mount MySQL Databases on Host
            - ./var/lib/mysql:/var/lib/mysql
            # Mount MySQL Log Files on Host
            - ./var/log/mysql:/var/log/mysql
        ports:
            - "3306:3306"
        restart: on-failure
    redis:
        image: redis
        container_name: ${PROJECT_NAME}_redis
        ports:
            - "6379:6379"
    mailhog:
        image: mailhog/mailhog
        container_name: ${PROJECT_NAME}_mailhog
        hostname: mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
volumes:
  web-data-volume:
