version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.apache
            args:
                - ROOT_USER_PASS=root
                - DEV_USER_PASS=dev
        volumes:
            - ./var/log/apache2:/var/log/apache2
            # Example of a Host Mounted Volume
            - ./var/www/html:/var/www/html
            # Example of a Named Data Volume
            #- web-data-volume:/var/www/html
        ports:
            - "80:80"
            - "443:443"
            - "1080:1080"
            - "1025:1025"
            - "2222:22"
        links:
            - db:mysql
            - redis:redis
        environment:
            - DOCUMENT_ROOT=/var/www/html
            - ENVIRONMENT=Development
        restart: always
    db:
        build:
            context: .
            dockerfile: Dockerfile.mysql
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            # - MYSQL_ROOT_PASSWORD
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=dev
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        restart: always
    redis:
        image: redis
        ports:
            - 6379:6379
volumes:
  web-data-volume:
